name: Remote Build and Push
on:
  repository_dispatch:
    types: [trigger-docker-build]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. Clone the project submitted in the form
      - name: Clone Developer Project
        run: git clone ${{ github.event.client_payload.git_url }} external-project

      # 2. Build the Docker Image
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push
        run: |
          cd external-project
          docker build -t ${{ secrets.DOCKER_USERNAME }}/my-app:${{ github.event.client_payload.image_tag }} .
          docker push ${{ secrets.DOCKER_USERNAME }}/my-app:${{ github.event.client_payload.image_tag }}